# Generated by Django 3.2.6 on 2021-11-28 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 19, 56, 42, 683573)),
        ),
    ]
