# Generated by Django 3.2.6 on 2021-11-28 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogpost_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='new',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 19, 58, 15, 3552)),
        ),
    ]
