# Generated by Django 3.2.6 on 2021-11-28 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211128_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 19, 59, 29, 786653)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='new',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
